---
  - name: setup zfs-auto-snapshot cron jobs
    template: 
      src: "zfs-auto-snapshot.cron.{{ item }}.j2"
      dest: "/etc/cron.{{ item }}/zfs-auto-snapshot"
      owner: "root"
      group: "root"
      mode: "u=rwx,g=rx,o=rx"
    with_items:
      - hourly
      - daily
      - weekly
      - monthly

  - name: setup man page for zfs-auto-snapshot
    copy:
      src: "zfs-auto-snapshot/src/zfs-auto-snapshot.8"
      dest: "/usr/local/share/man/man8/zfs-auto-snapshot.8"
      owner: "root"
      group: "root"
      mode: "u=rw,g=r,o=r"

  - name: setup zfs-auto-snapshot tool
    copy:
      src: "zfs-auto-snapshot/src/zfs-auto-snapshot.sh"
      dest: "/usr/local/sbin/zfs-auto-snapshot"
      owner: "root"
      group: "root"
      mode: "u=rwx,g=rx,o=rx"