# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "ansible-zfsonlinux"
    v.memory = 512
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "ansible-zfsonlinux"
  config.vm.network :private_network, ip: "192.168.138.2"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define "ansible-zfsonlinux" do |ansible_zfsonlinux|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.inventory_path = "inventory.yml"
    ansible.sudo = true
  end

end
